export const SET_ALL_CITY_LIST = 'SET_ALL_CITY_LIST';
export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_MENUTREEDATA = 'SET_MENUTREEDATA';
export const SET_AUTHBUTTON = 'SET_AUTHBUTTON';
export const SET_AUTHROUTES = 'SET_AUTHROUTES';